services:
  backend:
    build:
      context: ../
    command:
      [
        "python3",
        "/root/google-cloud-sdk/bin/dev_appserver.py",
        "--enable_host_checking=false",
        "--enable_watching_go_path=true",
        "--default_gcs_bucket_name=default",
        "--log_level=debug",
        "--admin_host=0.0.0.0",
        "--host=0.0.0.0",
        "--port=8881",
        "--storage_path=/data",
        "--runtime_python_path=/usr/bin/python3",
        "--application=app-test",
        "--datastore_consistency_policy=consistent",
        "--require_indexes=true",
        "/app/app.yaml"
      ]
    ports:
      - "8881:8881"
    volumes:
      - .:/app
    environment:
      GOOGLE_CLOUD_PROJECT: 'app-test'
      APPLICATION_ID: "dev~app-test"
  admin:
    image: "caddy:2-alpine"
    ports:
      - "8000:8000"
    command: >
      sh -c "echo -e \":8000 {\\n  reverse_proxy {\\n  to backend:8000\\n  header_up Origin http://0.0.0.0:8000\\n}\\n}\" > /Caddyfile && caddy run --config /Caddyfile"
    depends_on:
      - backend