services:
  datastore:
    build:
      context: ../
    volumes:
      - ./tmp:/opt/datastore/data
    ports:
      - "8081:8081"
    command:
      [
        "gcloud",
        "--quiet",
        "beta",
        "emulators",
        "datastore",
        "start",
        "--consistency=1",
        "--host-port=0.0.0.0:8081",
        "--data-dir=/opt/datastore/data"
      ]
    environment:
      CLOUDSDK_CORE_PROJECT: app-test
  dsadmin:
    image: "ghcr.io/remko/dsadmin:latest"
    depends_on:
      - datastore
    ports:
      - "8082:8080"
    environment:
      DATASTORE_PROJECT_ID: app-test
      DATASTORE_EMULATOR_HOST: "datastore:8081"
  backend:
    build:
      context: ../
    command:
      [
        "/root/google-cloud-sdk/bin/dev_appserver.py",
        "--enable_host_checking=false",
        "--enable_watching_go_path=true",
        "--log_level=debug",
        "--admin_host=0.0.0.0",
        "--host=0.0.0.0",
        "--port=8080",
        "--storage_path=/data",
        "--application=app-test",
        "/app/app.yaml"
      ]
    environment:
      GOOGLE_CLOUD_PROJECT: 'app-test'
      DATASTORE_EMULATOR_HOST: "datastore:8081"
    volumes:
      - .:/app
    depends_on:
      - datastore
    ports:
      - "8080:8080"
  admin:
    image: "caddy:2-alpine"
    ports:
      - "8000:8000"
    command: >
      sh -c "echo -e \":8000 {\\n  reverse_proxy {\\n  to backend:8000\\n  header_up Origin http://0.0.0.0:8000\\n}\\n}\" > /Caddyfile && caddy run --config /Caddyfile"
    depends_on:
      - backend